"""refactor: rename index_in_session to seq_in_session and remove Battle.conversation

Revision ID: 92005f75b0c0
Revises: d7e4e8fa91aa
Create Date: 2025-10-24 23:31:19.260548

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92005f75b0c0'
down_revision: Union[str, Sequence[str], None] = 'd7e4e8fa91aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('battle_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('turn_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('battle_seq_in_session', sa.Integer(), nullable=False),
    sa.Column('turn_seq', sa.Integer(), nullable=False),
    sa.Column('seq_in_turn', sa.Integer(), nullable=False),
    sa.Column('session_seq', sa.Integer(), nullable=True),
    sa.Column('side', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_battle_id'), 'messages', ['battle_id'], unique=False)
    op.create_index(op.f('ix_messages_battle_seq_in_session'), 'messages', ['battle_seq_in_session'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_message_id'), 'messages', ['message_id'], unique=True)
    op.create_index(op.f('ix_messages_seq_in_turn'), 'messages', ['seq_in_turn'], unique=False)
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_messages_session_seq'), 'messages', ['session_seq'], unique=False)
    op.create_index(op.f('ix_messages_turn_id'), 'messages', ['turn_id'], unique=False)
    op.create_index(op.f('ix_messages_turn_seq'), 'messages', ['turn_seq'], unique=False)
    op.create_table('turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turn_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('battle_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('battle_seq_in_session', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('user_input', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turns_battle_id'), 'turns', ['battle_id'], unique=False)
    op.create_index(op.f('ix_turns_battle_seq_in_session'), 'turns', ['battle_seq_in_session'], unique=False)
    op.create_index(op.f('ix_turns_created_at'), 'turns', ['created_at'], unique=False)
    op.create_index(op.f('ix_turns_seq'), 'turns', ['seq'], unique=False)
    op.create_index(op.f('ix_turns_session_id'), 'turns', ['session_id'], unique=False)
    op.create_index(op.f('ix_turns_turn_id'), 'turns', ['turn_id'], unique=True)
    op.add_column('battles', sa.Column('seq_in_session', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_battles_seq_in_session'), 'battles', ['seq_in_session'], unique=False)
    op.drop_column('battles', 'conversation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battles', sa.Column('conversation', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_battles_seq_in_session'), table_name='battles')
    op.drop_column('battles', 'seq_in_session')
    op.drop_index(op.f('ix_turns_turn_id'), table_name='turns')
    op.drop_index(op.f('ix_turns_session_id'), table_name='turns')
    op.drop_index(op.f('ix_turns_seq'), table_name='turns')
    op.drop_index(op.f('ix_turns_created_at'), table_name='turns')
    op.drop_index(op.f('ix_turns_battle_seq_in_session'), table_name='turns')
    op.drop_index(op.f('ix_turns_battle_id'), table_name='turns')
    op.drop_table('turns')
    op.drop_index(op.f('ix_messages_turn_seq'), table_name='messages')
    op.drop_index(op.f('ix_messages_turn_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_session_seq'), table_name='messages')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_seq_in_turn'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_battle_seq_in_session'), table_name='messages')
    op.drop_index(op.f('ix_messages_battle_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
