"""add sessions battles votes tables

Revision ID: b1c5dfd43f55
Revises: 001
Create Date: 2025-10-21 18:59:50.881620

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b1c5dfd43f55'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('battles', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(op.f('battles_battle_id_key'), 'battles', type_='unique')
    op.drop_index(op.f('idx_battles_created_at'), table_name='battles')
    op.drop_index(op.f('idx_battles_session_id'), table_name='battles')
    op.drop_index(op.f('idx_battles_session_status'), table_name='battles')
    op.drop_index(op.f('idx_battles_status'), table_name='battles')
    op.create_index(op.f('ix_battles_battle_id'), 'battles', ['battle_id'], unique=True)
    op.create_index(op.f('ix_battles_created_at'), 'battles', ['created_at'], unique=False)
    op.create_index(op.f('ix_battles_session_id'), 'battles', ['session_id'], unique=False)
    op.create_index(op.f('ix_battles_status'), 'battles', ['status'], unique=False)
    op.drop_index(op.f('idx_model_stats_elo_score'), table_name='model_stats')
    op.drop_index(op.f('idx_model_stats_license'), table_name='model_stats')
    op.drop_index(op.f('idx_model_stats_organization'), table_name='model_stats')
    op.drop_index(op.f('idx_model_stats_vote_count'), table_name='model_stats')
    op.drop_constraint(op.f('model_stats_model_id_key'), 'model_stats', type_='unique')
    op.create_index(op.f('ix_model_stats_elo_score'), 'model_stats', ['elo_score'], unique=False)
    op.create_index(op.f('ix_model_stats_model_id'), 'model_stats', ['model_id'], unique=True)
    op.create_index(op.f('ix_model_stats_vote_count'), 'model_stats', ['vote_count'], unique=False)
    op.alter_column('sessions', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sessions', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('idx_sessions_created_at'), table_name='sessions')
    op.drop_index(op.f('idx_sessions_user_id'), table_name='sessions')
    op.drop_constraint(op.f('sessions_session_id_key'), 'sessions', type_='unique')
    op.create_index(op.f('ix_sessions_last_active_at'), 'sessions', ['last_active_at'], unique=False)
    op.create_index(op.f('ix_sessions_session_id'), 'sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.alter_column('votes', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    # Skip error_message type change (TEXT is fine)
    op.drop_index(op.f('idx_votes_processing_status'), table_name='votes')
    op.drop_index(op.f('idx_votes_session_id'), table_name='votes')
    op.drop_index(op.f('idx_votes_voted_at'), table_name='votes')
    op.drop_constraint(op.f('votes_battle_id_key'), 'votes', type_='unique')
    op.drop_constraint(op.f('votes_vote_id_key'), 'votes', type_='unique')
    op.create_index(op.f('ix_votes_battle_id'), 'votes', ['battle_id'], unique=True)
    op.create_index(op.f('ix_votes_processing_status'), 'votes', ['processing_status'], unique=False)
    op.create_index(op.f('ix_votes_session_id'), 'votes', ['session_id'], unique=False)
    op.create_index(op.f('ix_votes_vote_id'), 'votes', ['vote_id'], unique=True)
    op.create_index(op.f('ix_votes_voted_at'), 'votes', ['voted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_voted_at'), table_name='votes')
    op.drop_index(op.f('ix_votes_vote_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_session_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_processing_status'), table_name='votes')
    op.drop_index(op.f('ix_votes_battle_id'), table_name='votes')
    op.create_unique_constraint(op.f('votes_vote_id_key'), 'votes', ['vote_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('votes_battle_id_key'), 'votes', ['battle_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_votes_voted_at'), 'votes', ['voted_at'], unique=False)
    op.create_index(op.f('idx_votes_session_id'), 'votes', ['session_id'], unique=False)
    op.create_index(op.f('idx_votes_processing_status'), 'votes', ['processing_status'], unique=False)
    # Skip error_message type change (TEXT is fine)
    op.alter_column('votes', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_last_active_at'), table_name='sessions')
    op.create_unique_constraint(op.f('sessions_session_id_key'), 'sessions', ['session_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('idx_sessions_created_at'), 'sessions', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('sessions', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('sessions', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_model_stats_vote_count'), table_name='model_stats')
    op.drop_index(op.f('ix_model_stats_model_id'), table_name='model_stats')
    op.drop_index(op.f('ix_model_stats_elo_score'), table_name='model_stats')
    op.create_unique_constraint(op.f('model_stats_model_id_key'), 'model_stats', ['model_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_model_stats_vote_count'), 'model_stats', [sa.literal_column('vote_count DESC')], unique=False)
    op.create_index(op.f('idx_model_stats_organization'), 'model_stats', ['organization'], unique=False)
    op.create_index(op.f('idx_model_stats_license'), 'model_stats', ['license'], unique=False)
    op.create_index(op.f('idx_model_stats_elo_score'), 'model_stats', [sa.literal_column('elo_score DESC')], unique=False)
    op.drop_index(op.f('ix_battles_status'), table_name='battles')
    op.drop_index(op.f('ix_battles_session_id'), table_name='battles')
    op.drop_index(op.f('ix_battles_created_at'), table_name='battles')
    op.drop_index(op.f('ix_battles_battle_id'), table_name='battles')
    op.create_index(op.f('idx_battles_status'), 'battles', ['status'], unique=False)
    op.create_index(op.f('idx_battles_session_status'), 'battles', ['session_id', 'status'], unique=False)
    op.create_index(op.f('idx_battles_session_id'), 'battles', ['session_id'], unique=False)
    op.create_index(op.f('idx_battles_created_at'), 'battles', [sa.literal_column('created_at DESC')], unique=False)
    op.create_unique_constraint(op.f('battles_battle_id_key'), 'battles', ['battle_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('battles', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
