"""VLA Arena MVP schema

Revision ID: b3a87a3d54ec
Revises: 
Create Date: 2025-11-04 23:58:39.438048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'b3a87a3d54ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('battle_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('seq_in_session', sa.Integer(), nullable=False),
    sa.Column('left_model_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('right_model_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battles_battle_id'), 'battles', ['battle_id'], unique=True)
    op.create_index(op.f('ix_battles_created_at'), 'battles', ['created_at'], unique=False)
    op.create_index(op.f('ix_battles_seq_in_session'), 'battles', ['seq_in_session'], unique=False)
    op.create_index(op.f('ix_battles_session_id'), 'battles', ['session_id'], unique=False)
    op.create_index(op.f('ix_battles_status'), 'battles', ['status'], unique=False)
    op.create_table('model_stats_by_robot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('robot_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('elo_score', sa.Integer(), nullable=False),
    sa.Column('elo_ci', sa.Float(), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.Column('win_count', sa.Integer(), nullable=False),
    sa.Column('loss_count', sa.Integer(), nullable=False),
    sa.Column('tie_count', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_stats_by_robot_elo_score'), 'model_stats_by_robot', ['elo_score'], unique=False)
    op.create_index(op.f('ix_model_stats_by_robot_model_id'), 'model_stats_by_robot', ['model_id'], unique=False)
    op.create_index(op.f('ix_model_stats_by_robot_robot_id'), 'model_stats_by_robot', ['robot_id'], unique=False)
    op.create_index(op.f('ix_model_stats_by_robot_vote_count'), 'model_stats_by_robot', ['vote_count'], unique=False)
    op.create_table('model_stats_total',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('elo_score', sa.Integer(), nullable=False),
    sa.Column('elo_ci', sa.Float(), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.Column('win_count', sa.Integer(), nullable=False),
    sa.Column('loss_count', sa.Integer(), nullable=False),
    sa.Column('tie_count', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('organization', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('license', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_stats_total_elo_score'), 'model_stats_total', ['elo_score'], unique=False)
    op.create_index(op.f('ix_model_stats_total_model_id'), 'model_stats_total', ['model_id'], unique=True)
    op.create_index(op.f('ix_model_stats_total_vote_count'), 'model_stats_total', ['vote_count'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('robot_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('scene_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_last_active_at'), 'sessions', ['last_active_at'], unique=False)
    op.create_index(op.f('ix_sessions_session_id'), 'sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turn_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('battle_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('battle_seq_in_session', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('instruction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turns_battle_id'), 'turns', ['battle_id'], unique=False)
    op.create_index(op.f('ix_turns_battle_seq_in_session'), 'turns', ['battle_seq_in_session'], unique=False)
    op.create_index(op.f('ix_turns_created_at'), 'turns', ['created_at'], unique=False)
    op.create_index(op.f('ix_turns_seq'), 'turns', ['seq'], unique=False)
    op.create_index(op.f('ix_turns_session_id'), 'turns', ['session_id'], unique=False)
    op.create_index(op.f('ix_turns_turn_id'), 'turns', ['turn_id'], unique=True)
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('battle_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('robot_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('scene_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('left_model_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('right_model_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('vote', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('processing_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('voted_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votes_battle_id'), 'votes', ['battle_id'], unique=True)
    op.create_index(op.f('ix_votes_processing_status'), 'votes', ['processing_status'], unique=False)
    op.create_index(op.f('ix_votes_robot_id'), 'votes', ['robot_id'], unique=False)
    op.create_index(op.f('ix_votes_scene_id'), 'votes', ['scene_id'], unique=False)
    op.create_index(op.f('ix_votes_session_id'), 'votes', ['session_id'], unique=False)
    op.create_index(op.f('ix_votes_vote_id'), 'votes', ['vote_id'], unique=True)
    op.create_index(op.f('ix_votes_voted_at'), 'votes', ['voted_at'], unique=False)
    op.create_table('worker_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('votes_processed', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_status')
    op.drop_index(op.f('ix_votes_voted_at'), table_name='votes')
    op.drop_index(op.f('ix_votes_vote_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_session_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_scene_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_robot_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_processing_status'), table_name='votes')
    op.drop_index(op.f('ix_votes_battle_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_turns_turn_id'), table_name='turns')
    op.drop_index(op.f('ix_turns_session_id'), table_name='turns')
    op.drop_index(op.f('ix_turns_seq'), table_name='turns')
    op.drop_index(op.f('ix_turns_created_at'), table_name='turns')
    op.drop_index(op.f('ix_turns_battle_seq_in_session'), table_name='turns')
    op.drop_index(op.f('ix_turns_battle_id'), table_name='turns')
    op.drop_table('turns')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_last_active_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_model_stats_total_vote_count'), table_name='model_stats_total')
    op.drop_index(op.f('ix_model_stats_total_model_id'), table_name='model_stats_total')
    op.drop_index(op.f('ix_model_stats_total_elo_score'), table_name='model_stats_total')
    op.drop_table('model_stats_total')
    op.drop_index(op.f('ix_model_stats_by_robot_vote_count'), table_name='model_stats_by_robot')
    op.drop_index(op.f('ix_model_stats_by_robot_robot_id'), table_name='model_stats_by_robot')
    op.drop_index(op.f('ix_model_stats_by_robot_model_id'), table_name='model_stats_by_robot')
    op.drop_index(op.f('ix_model_stats_by_robot_elo_score'), table_name='model_stats_by_robot')
    op.drop_table('model_stats_by_robot')
    op.drop_index(op.f('ix_battles_status'), table_name='battles')
    op.drop_index(op.f('ix_battles_session_id'), table_name='battles')
    op.drop_index(op.f('ix_battles_seq_in_session'), table_name='battles')
    op.drop_index(op.f('ix_battles_created_at'), table_name='battles')
    op.drop_index(op.f('ix_battles_battle_id'), table_name='battles')
    op.drop_table('battles')
    # ### end Alembic commands ###
