"""Change session user_id from int to varchar

Revision ID: d7e4e8fa91aa
Revises: 185323a1d7b8
Create Date: 2025-10-23 00:45:51.781019

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd7e4e8fa91aa'
down_revision: Union[str, Sequence[str], None] = '185323a1d7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('votes', 'error_message',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('votes', 'error_message',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sessions', 'user_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
